#!/usr/bin/env zsh

# setup aurutils

# repo name
repo_name="custom"

# path to repo
repo_dir="$HOME/Packages"

echo "Setup aurutils repo..."
echo "Name: $repo_name"
echo "Path: $repo_dir"

read -s -k "?Press any key continue" && echo

echo " * Create repo directory"
mkdir -p $repo_dir &>/dev/null
[[ $? -eq 0 ]] || \
  { echo "failed to create repo path"; exit 1 }

echo " * Initialize package database..."
cd $repo_dir
repo-add -R $repo_name.db.tar
[[ $? -eq 0 ]] || \
  { echo "failed to create repo db"; exit 1 }

echo " * Update $USER's pacman.conf"
local_temp="$(mktemp)"
local_conf="$HOME/.pacman.conf"
cp $local_conf $local_temp &>/dev/null
echo "\n[$repo_name]" >> $local_temp
echo "SigLevel = Optional TrustAll" >> $local_temp
echo "Server = file://$repo_dir" >> $local_temp
cp -b $local_temp $local_conf -S .backup

echo " * Update system pacman.conf"
sys_temp="$(mktemp)"
sys_conf="/etc/pacman.conf"
cp -p $sys_conf $sys_temp
echo "\nInclude = $HOME/.pacman.conf" >> $sys_temp
sudo cp -pb $sys_temp $sys_conf -S .backup

echo " * Sync pacman db"
sudo pacman -Sy

echo "Done!"
exit 0

# vim: ft=zsh ts=2 sw=2 et:
