#!/usr/bin/env zsh

# setup vim

# source
src_url=${URL:-"https://git.linuxit.us/spider/vim"}
tpo_url="https://tpo.pe/pathogen.vim"

# install to
dest_dir="$HOME/.vim"

# plugins
plugin_lst="$dest_dir/plugins.txt"

# color output (msg,info,err,reset)
m='\033[1;35m'; i='\033[1;32m'; e='\033[1;31m'; n='\033[0m'

echo "${m}Installing vim setup...${n}"
echo "${m}Source: ${i}$src_url${n}"
echo "${m}Target: ${i}$dest_dir${n}"
echo "${i}"
vared -cp "Confirm (y/n)? " ans
[[ "$ans" =~ ^[Yy]$ ]] || exit 1

# clone repo
if test -d $dest_dir
then
  echo "${e}Target '${i}$dest_dir${m}' already exists!${n}"
  exit 1
else
  if git clone $src_url $dest_dir
  then
    echo "${m}Cloned repo to ${i}$dest_dir${n}"
  else
    echo "${e}Failed to clone repo!${n}"
    exit 1
  fi
fi

local old_rc="$HOME/.vimrc"
if test -L $old_rc
then
  echo "${m}Target '${i}$old_rc${m}' is symlink!${n}"
  echo "${m}Removing symlink!${n}"
  rm $conf
fi

if test -f $old_rc
then
  echo "${m}Target '${i}$old_rc${m}' already exists!${n}"
  echo "${m}Created backup '${i}$old_rc.bak${m}'!${n}"
  mv -b $old_rc $old_rc.backup
fi

unset old_rc

echo "${m}Installing Pathogen...${n}"
local bundle_dir="$dest_dir/bundle"
local autoload_dir="$dest_dir/autoload"
mkdir -p $autoload_dir $bundle_dir 2>/dev/null
if ! curl -LSso $autoload_dir/$(basename "$tpo_url") $tpo_url
then
  echo "${e}Failed to install Pathogen!${n}"
  exit 1
fi

# get plugins
if test -f $plugin_lst
then
  mkdir -p $dest_dir/bundle &>/dev/null

  echo "Reading plugin list...${n}"
  typeset -A plugins
  while read name url
  do
    plugins[$name]="$url"
  done < $plugin_lst
  unset name url

  echo "Fetching plugins...${n}"
  for dest url in ${(kv)plugins}
  do
    dest="$dest_dir/bundle/$dest"
    if ! test -d $dest
    then
      git clone $url $dest
    fi
  done
  unset dest url
fi

echo "${i}Done${n}"
exit 0

# vim: ft=zsh ts=2 sw=2 et:
